import React, { Fragment } from 'react'
import Counter from '../components/counter/Counter'

export const Home: React.FC = () => {
  return (
    <Fragment>
      <h1>Redux + TypeScript</h1>
      <p>
        This app was generated by the Create React App template and bootstrapped
        with Redux, React Router, TypeScript, ESlint, Prettier.
      </p>
      <Counter />
    </Fragment>
  )
}
